// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVmLj55NjHkNHouYd13MDGbOF06kHErzY',
    appId: '1:15839048645:web:5986b0f5369c2ae6e3d1ac',
    messagingSenderId: '15839048645',
    projectId: 'pi5semestre-dbf95',
    authDomain: 'pi5semestre-dbf95.firebaseapp.com',
    storageBucket: 'pi5semestre-dbf95.firebasestorage.app',
    measurementId: 'G-6LSBVJSX3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQEueYjyWgY2l9IZYlIkgbsAmrtSIE4M',
    appId: '1:15839048645:android:984a9371de8e644de3d1ac',
    messagingSenderId: '15839048645',
    projectId: 'pi5semestre-dbf95',
    storageBucket: 'pi5semestre-dbf95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJILFbDI1CixEZ_eDJ4D8t3TFNwI2lcs',
    appId: '1:15839048645:ios:03a5d45d75b0a738e3d1ac',
    messagingSenderId: '15839048645',
    projectId: 'pi5semestre-dbf95',
    storageBucket: 'pi5semestre-dbf95.firebasestorage.app',
    iosBundleId: 'com.example.footflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVmLj55NjHkNHouYd13MDGbOF06kHErzY',
    appId: '1:15839048645:web:077bc43ef8e12604e3d1ac',
    messagingSenderId: '15839048645',
    projectId: 'pi5semestre-dbf95',
    authDomain: 'pi5semestre-dbf95.firebaseapp.com',
    storageBucket: 'pi5semestre-dbf95.firebasestorage.app',
    measurementId: 'G-1GNPDY0PJS',
  );

}